name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["enchancement"]
body:
  - type: textarea
    id: detail
    attributes:
      label: Detail
      description: Please explain the feature in details.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Reason for adding this feature.
    validations:
      required: true
  - type: textarea
    id: pseudo-code
    attributes:
      label: Pseudo Code
      description: If possible, Please include a pseudo code on how the feature will work.